# Generated by Django 4.0.4 on 2022-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_opis_opi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event name')),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=120)),
                ('manager', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Opi',
        ),
    ]
