# Generated by Django 4.0.4 on 2022-05-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_myclubuser_venue_event_attendes_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email_adress',
            field=models.EmailField(blank=True, max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.URLField(blank=True, max_length=120, verbose_name='Website adress'),
        ),
    ]
